FROM python:3.11-slim

WORKDIR /app

COPY requirements-streamlit.txt /app/requirements-streamlit.txt
RUN pip install --no-cache-dir -r /app/requirements-streamlit.txt

COPY app/ /app/app/

EXPOSE 8501

CMD ["streamlit", "run", "app/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
